name: Gradle Test CI

# Trigger workflow on push or pull request to main, develop, or feature branches
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest # Maybe we should change this to Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '25'
          cache: gradle

      - name: Run tests
        run: ./gradlew test
